--Secuencias
CREATE SEQUENCE SEC_Aulas
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Departamentos
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Despachos
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Grados
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Grupos
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Notas
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEC_Tutorias
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;


--Triggers asociados a secuencias
CREATE OR REPLACE TRIGGER TR_SEC_Aulas
BEFORE INSERT ON Aulas
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Aulas.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_A := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Departamentos
BEFORE INSERT ON Departamentos
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Departamentos.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_Dep := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Despachos
BEFORE INSERT ON Despachos
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Despachos.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_D := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Grados
BEFORE INSERT ON Grados
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Grados.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_G := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Grupos
BEFORE INSERT ON Grupos
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Grupos.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_Grup := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Notas
BEFORE INSERT ON Notas
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Notas.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_N := valorSec;
END;
/

CREATE OR REPLACE TRIGGER TR_SEC_Tutorias
BEFORE INSERT ON Tutorias
FOR EACH ROW
DECLARE 
	valorSec NUMBER := 0;
BEGIN
	SELECT SEC_Tutorias.NEXTVAL INTO valorSec FROM DUAL;
	:NEW.OID_T := valorSec;
END;
/
